/*
 * port.c
 *
 *  Created on: Sep 20, 2022
 *      Author: quangcaol
 */

#include "port.h"



void peripheral_deinit()
{
	LL_SYSTICK_DisableIT();
	RCC->APB1RSTR |= RCC_APB1RSTR_USART2RST; // Reset Usart
	RCC->APB1RSTR |= RCC_APB1RSTR_SPI2RST;
	LL_APB1_GRP1_DisableClock(LL_APB1_GRP1_PERIPH_SPI2);
	LL_APB1_GRP1_DisableClock(LL_APB1_GRP1_PERIPH_USART2);
	LL_AHB1_GRP1_DisableClock(LL_AHB1_GRP1_PERIPH_GPIOA);
	LL_AHB1_GRP1_DisableClock(LL_AHB1_GRP1_PERIPH_GPIOB);
	LL_AHB1_GRP1_DisableClock(LL_AHB1_GRP1_PERIPH_GPIOC);
	RCC->AHB1RSTR |= RCC_AHB1RSTR_GPIOBRST & RCC_AHB1RSTR_GPIOARST &  RCC_AHB1RSTR_GPIOCRST & RCC_AHB1RSTR_GPIOHRST;
	LL_RCC_DeInit();


	SCB->SHCSR &= ~( SCB_SHCSR_USGFAULTENA_Msk | \
	                 SCB_SHCSR_BUSFAULTENA_Msk | \
	                 SCB_SHCSR_MEMFAULTENA_Msk ) ;
}


